"""sim cart migration

Revision ID: 27f5f9fd28d4
Revises: ccafad22626f
Create Date: 2025-02-27 23:58:12.710319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f5f9fd28d4'
down_revision: Union[str, None] = 'ccafad22626f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sim_cart', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sim_cart', type_='unique')
    # ### end Alembic commands ###
