"""Initial company migration

Revision ID: 3ddb25dfd580
Revises: 4ccbd4cc3243
Create Date: 2025-02-26 16:52:11.741388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddb25dfd580'
down_revision: Union[str, None] = '4ccbd4cc3243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
