"""telecom_operator migration unique

Revision ID: 6642e162bb98
Revises: ab30c10447ce
Create Date: 2025-02-27 12:33:15.733948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6642e162bb98'
down_revision: Union[str, None] = 'ab30c10447ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telecom_operator_operator_name_key', 'telecom_operator', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('telecom_operator_operator_name_key', 'telecom_operator', ['operator_name'])
    # ### end Alembic commands ###
