"""telecom_operator migration unique

Revision ID: 69812d43c73a
Revises: d87c8477897b
Create Date: 2025-02-27 11:39:30.102050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69812d43c73a'
down_revision: Union[str, None] = 'd87c8477897b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'telecom_operator', ['operator_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telecom_operator', type_='unique')
    # ### end Alembic commands ###
