"""telecom_operator migration

Revision ID: d87c8477897b
Revises: c2fc2d03ed8c
Create Date: 2025-02-27 11:30:08.624116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87c8477897b'
down_revision: Union[str, None] = 'c2fc2d03ed8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telecom_operator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telecom_operator')
    # ### end Alembic commands ###
